float32 risk_time_cost
float32 risk_deviate_cost
float32 risk_total_cost
float32 risk_acc_cost
float32 State
float32 cos_value
float32 Safecheck
float32 CorridorPnt
float32 RcControlCost
float32 RcAndDeviateCost
float32 DeviationCost

# computation time calculate
float32 replan_traj_t_1
float32 replan_traj_t_2
float32 replan_yaw_t_1
float32 replan_yaw_t_2

float32 traj_generate_t_1
float32 traj_generate_t_2
float32 traj_generate_t_3
float32 traj_generate_t_4
float32 traj_generate_iter

float32 lc_replan_p1
float32 lc_replan_p2
float32 lc_replan_p3
float32 lc_replan_p4

float32 lc_traj_waypoint

float32 emergency_cal_time

# some operate state
float32 recover
float32 waypoint_check
float32 time_check
float32 get_replan_state_check
float32 traj_exe_time

float32 rhoTProgress
float32 finish_time