Header header

float64[] pos_x
float64[] pos_y
float64[] pos_z

float64[] vel_x
float64[] vel_y
float64[] vel_z

float64[] quaternion_w
float64[] quaternion_x
float64[] quaternion_y
float64[] quaternion_z

float64[] yaw_degree
float64[] pitch_degree
float64[] roll_degree

float64[] bodyrate_x
float64[] bodyrate_y
float64[] bodyrate_z

float64[] T1
float64[] T2
float64[] T3
float64[] T4

float64[] Omega1
float64[] Omega2
float64[] Omega3
float64[] Omega4
